# Generated by Django 4.1.3 on 2022-12-02 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_urlresults_address_urlresults_applicant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlresultsvalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='urlresultsvalue',
            name='url_result',
        ),
        migrations.DeleteModel(
            name='UrlResultAttributes',
        ),
        migrations.DeleteModel(
            name='UrlResultsValue',
        ),
    ]
