# Generated by Django 4.1.3 on 2022-12-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_urlresultsvalue_attribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlresults',
            name='record_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
