# Generated by Django 3.2.13 on 2022-12-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_urlresults_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
