# Generated by Django 4.1.4 on 2022-12-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_urls_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlresults',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlresults',
            name='applicant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlresults',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlresults',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlresults',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlresults',
            name='existing_solar_system',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlresults',
            name='job_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlresults',
            name='kw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlresults',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlresults',
            name='panel_upgrade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlresults',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlresults',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlresults',
            name='total_cost',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlresults',
            name='utility_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlresults',
            name='zip',
            field=models.TextField(blank=True, null=True),
        ),
    ]
