# Generated by Django 4.1.4 on 2022-12-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_urlresults_address_alter_urlresults_applicant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlresults',
            name='owner',
            field=models.TextField(blank=True, null=True),
        ),
    ]
